site_name: Awesome .Net Core Educations
site_url: https://mehdihadeli.github.io/awesome-dotnet-core-education/
site_description: A curated list of awesome articles and resources for learning and practicing about .Net Core and its related technologies.
docs_dir: docs
repo_name: mehdihadeli/awesome-dotnet-core-education
repo_url: https://github.com/mehdihadeli/awesome-dotnet-core-education
edit_uri: edit/main/docs/
theme: 
  name: material 
  #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate 
    - navigation.top
  font:
    text: Sora
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
nav:
  - .Net:
    - .Net : dotnet/dotnet.md
    - .Net 8: dotnet/dotnet8.md 
    - .Net 7: dotnet/dotnet7.md 
    - .Net 6: dotnet/dotnet6.md     
    - .Net 5: dotnet/dotnet5.md 
    - .Net Build: dotnet/build.md  
    - .Net Package Management: dotnet/package-management.md
    - .Net Standard: dotnet/dotnet-standard.md
    - .Net Template: dotnet/dotnet-template.md
    -  ASP.Net Core: dotnet/dotnet-core.md
    - .Net Core Architecture: dotnet/dotnet-core-architecture.md
    - .Net Core Tips: dotnet/dotnet-core-tips.md
    - .Net IL: dotnet/il.md
    -  Multi Target: dotnet/multi-target.md
    -  MetaPack: dotnet/metapack.md
    - global.json File: dotnet/global-json.md
  - ASP.NET Core:
    - ASP.NET Core: asp/asp-net.md 
    - ASP.NET Core 8 : asp/asp-net-8.md 
    - ASP.NET Core 7 : asp/asp-net-7.md 
    - ASP.NET Core 6: asp/asp-net-6.md 
  - .Net CLI: 
    - .Net CLI: dotnet-cli/dotnet-cli.md
    - .Net Tools: dotnet-cli/dotnet-tools.md
    - .Net Watch: dotnet-cli/dotnet-watch.md
    - Upgrade Assistant: dotnet-cli/upgrade-assistant.md
  - C#: 
    - C#: csharp/csharp.md
    - C# Versions:
      - C# 11: csharp/versions/11.md
      - C# 10: csharp/versions/10.md
      - C# 9: csharp/versions/9.md
      - C# 8: csharp/versions/8.md
      - C# 7: csharp/versions/7.md
    - Async: 
      - Async And Await: csharp/async/async-and-await.md
      - Async Best Practice: csharp/async/async-best-practice.md
      - Analyzers: csharp/async/analyzers.md
      - Async Collections: 
        - Async Collections: csharp/async/async-collections.md
        - Async Stream And IEnumerableAsync: csharp/async/async-collections/async-stream-and-ienumerableasync.md
        - Blocking Collection: csharp/async/async-collections/blocking-collection.md
        - Iterators: csharp/async/async-collections/iterators.md
        - Lazy Initialization: csharp/async/async-collections/lazy-initialization.md
      - Asynchronous Messaging: csharp/async/asynchronous-messaging.md
      - Async Local: csharp/async/asynclocal.md
      - Awaiter: csharp/async/awaiter.md
      - Cancellation: csharp/async/cancellation.md
      - Channels: csharp/async/channels.md
      - Concurrency Vs Parallelism: csharp/async/concurrency-vs-parallelism)
      - Configure Await: csharp/async/configure-await.md
      - Continuations.md: csharp/async/continuations.md
      - Cpu Bound: csharp/async/cpu-bound.md
      - Exception Handling: csharp/async/exception-handling)
      - Io Bound: csharp/async/io-bound.md
      - Synchronization Context: csharp/async/synchronization-context.md
      - SemaphoreSlim: csharp/async/semaphoreslim.md
      - State Machine: csharp/async/state-machine.md
      - TaskCompletionSource: csharp/async/task-completion-source.md
      - TPL & TAP: csharp/async/tpl-tap.md
      - Parallel For & Foreach: csharp/async/parallel-for-foreach.md
      - ThreadPool: csharp/async/thread-pool.md
      - Thread: csharp/async/thread.md
      - ValueTask: csharp/async/valuetask.md
      - Sync Over Async: csharp/async/sync-over-async.md
      - Resources: csharp/async/resources.md
    - Locking: 
        - Lock: csharp/locking/lock.md 
        - Monitor: csharp/locking/monitor.md 
        - Mutex: csharp/locking/mutex.md 
        - Semaphore: csharp/locking/semaphore.md
        - Thread Safty: csharp/locking/thread-safty.md
    - Collections & Data Structure:
      - Collections & Data Structure: csharp/collections/collection-data-structure.md
      - Enumerable: csharp/collections/enumerable.md
      - HashSet: csharp/collections/hashset.md
    - Boxing: csharp/boxing.md
    - Closure: csharp/closure.md
    - Constant: csharp/constant.md
    - Operator: csharp/implicit-explicit-operators.md
    - Linq: csharp/linq.md
    - Covariance: csharp/covariance.md
    - Required: csharp/required.md
    - Compiler & Lowering: compiler-lowering.md
    - Extension Methods: csharp/extension-methods.md
    - Nullable Reference Types : csharp/nullable-reference-types.md
    - Reflection & Assemblies: csharp/reflection.md
    - Null Check: csharp/null-check.md
    - Conditional Compilation & Assert: csharp/conditional-compilation-assert.md
    - Generic: csharp/generic.md
    - Types : csharp/types.md
    - Pattern Matching : csharp/pattern-matching.md
    - Span: csharp/span.md
    - Deconstruction: csharp/deconstruction.md
    - Record: csharp/record.md
    - Enum: csharp/enum.md
  - MAUI: maui.md
  - Blazor: blazor.md
  - Open Api: open-api.md
  - Source Generators: source-generators.md
  - Performance: performance.md
  - Health Check: health-check.md
  - Serialization: serialization.md
  - Generic Host: generic-host.md
  - Hosting: hosting.md
  - Kestrel: kestrel.md
  - Feature Flags: feature-flags.md
  - REST: rest.md
  - Middleware: middleware.md
  - Action Filters: action-filters.md
  - Configuration & Secrets : configuration-secrets.md
  - Options: options.md
  - HttContext: httpcontext.md
  - gRPC: grpc.md
  - WebSockets: web-sockets.md
  - SignalR: signalr.md
  - HttpClient: httpclient.md
  - WEB API: web-api.md
  - Lunch Urls & launchSettings: lunch-urls-launchsettings.md
  - Minimal API: minimal-api.md
  - ML.Net : ml-net.md
  - Background Tasks: background-tasks.md
  - Razor Pages: razor-pages.md
  - GraphQL: graphql.md
  - GitHub:
    - Git: github/git.md
    - GitHub: github/github.md
    - Release Notes: github/release-note.md
    - Git-Flow: github/git-flow.md
    - Conventional Commits: github/conventional-commits.md
    - Projects: github/projects.md
    - SSH: github/ssh.md
    - Copilot: github/copilot.md
    - GitHub SubModule: github/sub-module.md
  - Elastic Search: elastic-search.md
  - OData: odata.md
  - Debugging: debugging.md
  - Nuget & Pack: nuget-pack.md
  - API Versioning: api-versioning.md
  - Hosted Service: hosted-service.md
  - Routing: routing.md
  - Dependency Injection: dependency-injection.md
  - Security: 
    - Encryption And Data Protection: security/encryption.md
    - .Net Core Identity: security/dotnet-identity.md
    - Identity Server: security/identity-server.md
    - MSAL: security/msal.md
    - Authentication: security/authentication.md
    - Authorization: security/authorization.md
    - OAuth & OpenID Connect: security/oauth-opencid.md
    - Refresh Token: security/refresh-token.md
    - Revoking Token: security/revoking-token.md
    - Secret Management: security/secret-management.md
  - Logging And Auditing: logging.md
  - Distributed Tracing: distributed-tracing.md
  - CorrelationId: correlationId.md
  - Diagnostics: diagnostics.md
  - Testing: 
    - Testing: testing/testing.md
    - Unit Testing: testing/unit-testing.md
    - Integration Testing: testing/integration-testing.md
    - End-To-End Testing: testing/end-to-end-testing.md
    - Acceptance Testing: testing/acceptance-testing.md
    - Load Testing: testing/load-testing.md
    - Snapshot Testing: testing/snapshot-testing.md
    - Mutation Testing: testing/mutation-testing.md
    - Architectural Testing: testing/architectural-testing.md
    - Contract Testing: testing/contract-testing.md
    - Test Host And WebApplicationFactory: testing/test-host.md
    - Code Coverage & Analysis: testing/code-coverage-analysis.md
    - Mocking: testing/mocking.md
    - TDD: testing/tdd.md
    - BDD: testing/bdd.md
    - XUnit: testing/xunit.md
  - Exception && Validation: exception-validation.md
  - EF Core: 
    - EF Core: ef-core/ef-core.md
    - EF Core 8: ef-core/ef-core-8.md
    - EF Core 7: ef-core/ef-core-7.md
    - EF Core 6: ef-core/ef-core-6.md
    - EF Core 5: ef-core/ef-core-5.md
    - Expression Tree: ef-core/expression-tree.md
    - Explicit Loading: ef-core/explicit-loading.md
    - Eager Loading: ef-core/eager-loading.md
    - Lazy Loading: ef-core/lazy-loading.md
    - Projection: ef-core/projection.md
    - Performance: ef-core/performance.md
    - Transaction: ef-core/transaction.md
    - Soft Delete: ef-core/soft-delete.md
    - Query Filters: ef-core/query-filter.md
    - Reverse Engineering: ef-core/reverse-engineering.md
    - Seed : ef-core/seed.md
    - Own Types : ef-core/own-types.md
    - Split Query: ef-core/split-query.md
    - Compiled Query: ef-core/compiled-query.md
    - Interceptor: ef-core/interceptor.md
    - Change Tracking: ef-core/change-tracking.md
  - Environment: environment.md
  - ID: id.md
  - Mediator: mediator.md
  - Mapping: mapping.md
  - Caching: caching.md
  - Aspire: aspire.md
  - Model Binding: model-binding.md
  - Benchmarking: benchmarking.md
  - Rate Limiting: rate-limiting.md
  - Stronglt Type ID: strongly-type-id.md
  - Semantic Versioning: semantic-versioning.md
  - Migrations: migration.md
  - Service Discovery: service-discovery.md
  - Dapper: dapper.md
  - Multi Tenancy: multi-tenancy.md
  - Orleans: orleans.md
  - Localization: localization.md
  - WebHook: webhook.md
  - Code Generation: code-generation.md
  - Roslyn Analizers: roslyn-analizers.md
  - Tools:
    - Cake: tools/cake.md
    - Nuke: tools/nuke.md
  - Remote Development:
    - DevContainers: remote-development/devcontainers.md
    - GitHub Codespace: remote-development/github-codespace.md
    - Gitpod: remote-development/gitpod.md
  - IDE & Tools: 
    - Reharper & Rider: ide-tools/resharper-rider.md
    - Decompile & DotPeek: ide-tools/decompile.md
    - DotMemory: ide-tools/dotmemory.md
    - DotTrace: ide-tools/dottrace.md
    - Dotcover: ide-tools/dotcover.md
    - DataGrip: ide-tools/datagrip.md
    - VSCode: ide-tools/vscode.md
    - Terminal & Dotfiles: ide-tools/terminal-dotfiles.md
    - DotNet Intreactive: ide-tools/dotnet-interactive.md
    - WSL: ide-tools/wsl.md
  - Rx.Net: rx.md
  - Regex: regex.md
  - Documentation: documentation.md
  - Formatting: formatting.md
  - Others: others.md


copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli
